# Generated by Django 5.2.6 on 2026-06-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='supabase_uid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
