# Generated by Django 5.1.15 on 2026-06-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminuser_delete_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='admins/'),
        ),
    ]
