# Generated by Django 5.1.15 on 2026-06-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_authtokenrevocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
