-- ==========================================
-- Shresht Library Management System
-- PostgreSQL Database Schema for Supabase
-- ==========================================
-- Supabase Project Connection Details:
-- URL: https://crrfhaaqeainuqzkmged.supabase.co
-- Publishable Key: sb_publishable_m0z-t34QvHCIjmiFc9n4mQ_yy6epwbt
-- ==========================================
-- Updated for project migrations through:
-- accounts 0004, attendance 0003, core 0003, library 0003,
-- memberships 0002, notifications 0002, payments 0002,
-- seats 0002, students 0002, study 0001.
--
-- This snapshot covers project app tables. Django built-in auth,
-- admin, sessions, contenttypes, and migrations tables are managed
-- by Django's bundled migrations.
-- ==========================================

-- 1. Custom Users & Staff Administrators
CREATE TABLE "accounts_customuser" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "password" varchar(128) NOT NULL,
    "last_login" timestamp with time zone NULL,
    "is_superuser" boolean NOT NULL DEFAULT false,
    "username" varchar(150) NOT NULL UNIQUE,
    "first_name" varchar(150) NOT NULL DEFAULT '',
    "last_name" varchar(150) NOT NULL DEFAULT '',
    "is_staff" boolean NOT NULL DEFAULT false,
    "date_joined" timestamp with time zone NOT NULL DEFAULT now(),
    "email" varchar(254) NULL UNIQUE,
    "mobile" varchar(15) NULL UNIQUE,
    "role" varchar(20) NOT NULL DEFAULT 'student',
    "otp" varchar(6) NULL,
    "otp_expiry" timestamp with time zone NULL,
    "is_active" boolean NOT NULL DEFAULT true,
    "supabase_uid" uuid NULL UNIQUE
);

CREATE TABLE "accounts_adminuser" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "username" varchar(150) NOT NULL UNIQUE,
    "email" varchar(254) NULL UNIQUE,
    "password" varchar(128) NOT NULL,
    "first_name" varchar(150) NOT NULL DEFAULT '',
    "last_name" varchar(150) NOT NULL DEFAULT '',
    "mobile" varchar(15) NULL UNIQUE,
    "role" varchar(20) NOT NULL DEFAULT 'admin',
    "permissions" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "profile_image" varchar(100) NULL,
    "is_active" boolean NOT NULL DEFAULT true,
    "date_joined" timestamp with time zone NOT NULL DEFAULT now(),
    "last_login" timestamp with time zone NULL,
    "supabase_uid" uuid NULL UNIQUE,
    "created_by_id" bigint NULL REFERENCES "accounts_adminuser" ("id") ON DELETE SET NULL
);

-- 2. Student Profiles & Referral Tracking
CREATE TABLE "students_studentprofile" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL UNIQUE REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE,
    "student_id" varchar(20) NULL UNIQUE,
    "middle_name" varchar(100) NULL,
    "goal" varchar(50) NOT NULL DEFAULT 'Other',
    "dob" date NULL,
    "gender" varchar(20) NOT NULL DEFAULT 'Other',
    "caste" varchar(50) NULL,
    "address" text NULL,
    "profile_photo" varchar(100) NULL,
    "parent_mobile" varchar(15) NULL,
    "status" varchar(20) NOT NULL DEFAULT 'LIVE',
    "suspension_reason" text NULL,
    "suspended_at" timestamp with time zone NULL,
    "suspended_by_id" bigint NULL REFERENCES "accounts_adminuser" ("id") ON DELETE SET NULL,
    "preferred_language" varchar(10) NOT NULL DEFAULT 'en',
    "referred_by_id" bigint NULL REFERENCES "students_studentprofile" ("id") ON DELETE SET NULL,
    "created_at" timestamp with time zone NULL DEFAULT now(),
    "updated_at" timestamp with time zone NULL DEFAULT now()
);

CREATE TABLE "students_referralcode" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "student_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE,
    "code" varchar(20) NOT NULL UNIQUE,
    "used_by_count" integer NOT NULL DEFAULT 0,
    "benefit_given" varchar(255) NULL
);

CREATE TABLE "students_referralhistory" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "referrer_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE,
    "referred_student_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE,
    "applied_at" timestamp with time zone NOT NULL DEFAULT now()
);

-- 3. Secure QR Attendance
CREATE TABLE "attendance_qrcode" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "token" uuid NULL UNIQUE,
    "code" varchar(255) NOT NULL UNIQUE,
    "qr_hash" text NOT NULL DEFAULT '',
    "created_by_id" bigint NULL REFERENCES "accounts_adminuser" ("id") ON DELETE SET NULL,
    "valid_date" date NOT NULL,
    "is_expired" boolean NOT NULL DEFAULT false,
    "is_active" boolean NOT NULL DEFAULT true,
    "generation_method" varchar(20) NOT NULL DEFAULT 'MANUAL',
    "expiry_timestamp" timestamp with time zone NOT NULL,
    "expires_at" timestamp with time zone NULL,
    "created_at" timestamp with time zone NULL DEFAULT now()
);

CREATE TABLE "attendance_attendance" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "student_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE,
    "date" date NOT NULL,
    "time_in" time NOT NULL DEFAULT LOCALTIME,
    "qr_code_id" bigint NULL REFERENCES "attendance_qrcode" ("id") ON DELETE SET NULL,
    "is_present" boolean NOT NULL DEFAULT true,
    "is_manual" boolean NOT NULL DEFAULT false,
    "method" varchar(20) NOT NULL DEFAULT 'QR',
    "marked_at" timestamp with time zone NULL DEFAULT now(),
    "marked_by_id" bigint NULL REFERENCES "accounts_adminuser" ("id") ON DELETE SET NULL,
    "note" text NULL,
    UNIQUE ("student_id", "date")
);

-- 4. Membership Plans & Student Memberships
CREATE TABLE "memberships_membershipplan" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(100) NOT NULL,
    "duration_months" integer NOT NULL,
    "duration_days" integer NOT NULL DEFAULT 30,
    "price" numeric(10, 2) NOT NULL,
    "benefits" jsonb NOT NULL DEFAULT '[]'::jsonb,
    "description" text NULL,
    "is_active" boolean NOT NULL DEFAULT true,
    "sort_order" integer NOT NULL DEFAULT 0,
    "created_at" timestamp with time zone NULL DEFAULT now(),
    "updated_at" timestamp with time zone NULL DEFAULT now()
);

CREATE TABLE "memberships_membership" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "student_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE,
    "plan_id" bigint NOT NULL REFERENCES "memberships_membershipplan" ("id") ON DELETE RESTRICT,
    "plan_name_snapshot" varchar(100) NOT NULL DEFAULT '',
    "price_snapshot" numeric(10, 2) NOT NULL DEFAULT 0,
    "start_date" date NOT NULL,
    "end_date" date NOT NULL,
    "status" varchar(20) NOT NULL DEFAULT 'active',
    "is_active" boolean NOT NULL DEFAULT true,
    "renewal_count" integer NOT NULL DEFAULT 0,
    "notes" text NULL,
    "created_by_id" bigint NULL REFERENCES "accounts_adminuser" ("id") ON DELETE SET NULL,
    "created_at" timestamp with time zone NULL DEFAULT now()
);

-- 5. Payment Ledger Transactions
CREATE TABLE "payments_payment" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "payment_id" varchar(30) NULL UNIQUE,
    "student_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE,
    "membership_id" bigint NULL REFERENCES "memberships_membership" ("id") ON DELETE SET NULL,
    "amount" numeric(10, 2) NOT NULL,
    "status" varchar(20) NOT NULL DEFAULT 'pending',
    "payment_mode" varchar(20) NOT NULL DEFAULT 'Cash',
    "method" varchar(20) NOT NULL DEFAULT 'CASH',
    "payment_date" date NOT NULL DEFAULT CURRENT_DATE,
    "transaction_id" varchar(100) NULL,
    "transaction_ref" varchar(100) NULL,
    "receipt_url" varchar(100) NULL,
    "notes" text NULL,
    "paid_at" timestamp with time zone NULL,
    "recorded_by_id" bigint NULL REFERENCES "accounts_adminuser" ("id") ON DELETE SET NULL,
    "verified_by_id" bigint NULL REFERENCES "accounts_adminuser" ("id") ON DELETE SET NULL,
    "verified_at" timestamp with time zone NULL,
    "refund_amount" numeric(10, 2) NULL,
    "refund_reason" text NULL,
    "refunded_at" timestamp with time zone NULL,
    "created_at" timestamp with time zone NULL DEFAULT now()
);

-- 6. Library Seats, Floors, Rows, and Change Logs
CREATE TABLE "seats_floor" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(50) NOT NULL UNIQUE,
    "description" text NULL,
    "order" integer NOT NULL DEFAULT 0,
    "is_active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "seats_seatrow" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "floor_id" bigint NOT NULL REFERENCES "seats_floor" ("id") ON DELETE CASCADE,
    "label" varchar(10) NOT NULL,
    "order" integer NOT NULL DEFAULT 0,
    UNIQUE ("floor_id", "label")
);

CREATE TABLE "seats_seat" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "row_ref_id" bigint NULL REFERENCES "seats_seatrow" ("id") ON DELETE SET NULL,
    "floor" varchar(50) NOT NULL,
    "row" varchar(10) NOT NULL,
    "seat_number" varchar(10) NOT NULL,
    "status" varchar(20) NOT NULL DEFAULT 'available',
    "student_id" bigint NULL UNIQUE REFERENCES "accounts_customuser" ("id") ON DELETE SET NULL,
    "assigned_at" timestamp with time zone NULL,
    "assigned_by_id" bigint NULL REFERENCES "accounts_adminuser" ("id") ON DELETE SET NULL,
    "notes" text NULL,
    UNIQUE ("floor", "row", "seat_number")
);

CREATE TABLE "seats_seatassignment" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "student_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE,
    "seat_id" bigint NOT NULL REFERENCES "seats_seat" ("id") ON DELETE CASCADE,
    "assigned_date" date NOT NULL DEFAULT CURRENT_DATE,
    "released_date" date NULL
);

CREATE TABLE "seats_seatchangelog" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "seat_id" bigint NOT NULL REFERENCES "seats_seat" ("id") ON DELETE CASCADE,
    "student_id" bigint NULL REFERENCES "accounts_customuser" ("id") ON DELETE SET NULL,
    "action" varchar(30) NOT NULL,
    "changed_by_id" bigint NULL REFERENCES "accounts_adminuser" ("id") ON DELETE SET NULL,
    "previous_seat_id" bigint NULL REFERENCES "seats_seat" ("id") ON DELETE SET NULL,
    "reason" text NULL,
    "changed_at" timestamp with time zone NOT NULL DEFAULT now()
);

-- 7. Firebase FCM Push Notifications Channel
CREATE TABLE "notifications_notification" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(200) NOT NULL,
    "body" text NOT NULL,
    "type" varchar(30) NOT NULL DEFAULT 'push',
    "target_group" varchar(20) NOT NULL DEFAULT 'all',
    "target" varchar(20) NOT NULL DEFAULT 'ALL',
    "goal_filter" varchar(50) NULL,
    "status_filter" varchar(20) NULL,
    "send_push" boolean NOT NULL DEFAULT true,
    "send_email" boolean NOT NULL DEFAULT false,
    "send_sms" boolean NOT NULL DEFAULT false,
    "scheduled_at" timestamp with time zone NULL,
    "sent_at" timestamp with time zone NULL,
    "total_recipients" integer NOT NULL DEFAULT 0,
    "success_count" integer NOT NULL DEFAULT 0,
    "failure_count" integer NOT NULL DEFAULT 0,
    "created_by_id" bigint NULL REFERENCES "accounts_adminuser" ("id") ON DELETE SET NULL,
    "created_at" timestamp with time zone NULL DEFAULT now()
);

CREATE TABLE "notifications_devicetoken" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "student_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE,
    "token" text NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE "notifications_studentnotification" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "student_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE,
    "notification_id" bigint NOT NULL REFERENCES "notifications_notification" ("id") ON DELETE CASCADE,
    "is_read" boolean NOT NULL DEFAULT false,
    "push_delivered" boolean NOT NULL DEFAULT false,
    "email_delivered" boolean NOT NULL DEFAULT false,
    "sms_delivered" boolean NOT NULL DEFAULT false,
    "delivered_at" timestamp with time zone NULL,
    "read_at" timestamp with time zone NULL
);

-- 8. Library Info, Facilities, Achievers, and Student Reviews
CREATE TABLE "library_libraryinfo" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(200) NOT NULL DEFAULT 'Shresht Library',
    "tagline" varchar(300) NULL,
    "description" text NULL,
    "feature_image" varchar(100) NULL,
    "address" text NULL,
    "phone_primary" varchar(20) NULL,
    "phone_secondary" varchar(20) NULL,
    "email" varchar(254) NULL,
    "website" varchar(200) NULL,
    "open_time" time NULL,
    "close_time" time NULL,
    "off_days" jsonb NOT NULL DEFAULT '[]'::jsonb,
    "rules" text NOT NULL,
    "facilities" text NOT NULL,
    "about" text NOT NULL,
    "google_maps_url" varchar(200) NULL,
    "instagram_url" varchar(200) NULL,
    "facebook_url" varchar(200) NULL,
    "updated_at" timestamp with time zone NULL DEFAULT now()
);

CREATE TABLE "library_facility" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(100) NOT NULL,
    "icon_key" varchar(50) NOT NULL DEFAULT '',
    "description" text NULL,
    "is_active" boolean NOT NULL DEFAULT true,
    "order" integer NOT NULL DEFAULT 0
);

CREATE TABLE "library_achiever" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(100) NOT NULL,
    "photo" varchar(100) NULL,
    "goal" varchar(100) NULL,
    "achievement" varchar(255) NOT NULL,
    "year" integer NOT NULL,
    "is_featured" boolean NOT NULL DEFAULT false,
    "is_active" boolean NOT NULL DEFAULT true,
    "order" integer NOT NULL DEFAULT 0,
    "created_at" timestamp with time zone NULL DEFAULT now()
);

CREATE TABLE "library_review" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "student_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE,
    "rating" integer NOT NULL,
    "comment" text NOT NULL,
    "is_approved" boolean NOT NULL DEFAULT false,
    "rejection_reason" text NULL,
    "approved_by_id" bigint NULL REFERENCES "accounts_adminuser" ("id") ON DELETE SET NULL,
    "approved_at" timestamp with time zone NULL,
    "created_at" timestamp with time zone NULL DEFAULT now(),
    "updated_at" timestamp with time zone NULL DEFAULT now()
);

-- 9. Study Timer and Hour Goals
CREATE TABLE "study_studysession" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "student_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE,
    "start_time" timestamp with time zone NOT NULL,
    "end_time" timestamp with time zone NULL,
    "duration_minutes" integer NOT NULL DEFAULT 0
);

CREATE TABLE "study_studygoal" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "student_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE,
    "date" date NOT NULL,
    "target_hours" numeric(4, 2) NOT NULL,
    "achieved_hours" numeric(4, 2) NOT NULL DEFAULT 0,
    UNIQUE ("student_id", "date")
);

-- 10. Global System Settings & Action Activity Logs
CREATE TABLE "core_globalsetting" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "key" varchar(100) NOT NULL UNIQUE,
    "value" text NOT NULL,
    "description" text NULL
);

CREATE TABLE "core_activitylog" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NULL REFERENCES "accounts_customuser" ("id") ON DELETE SET NULL,
    "admin_id" bigint NULL REFERENCES "accounts_adminuser" ("id") ON DELETE SET NULL,
    "action" varchar(255) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL DEFAULT now(),
    "ip_address" inet NULL,
    "details" jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- 11. Named Indexes From Current Django Models
CREATE INDEX "students_st_student_58f688_idx" ON "students_studentprofile" ("student_id");
CREATE INDEX "students_st_status_6012f4_idx" ON "students_studentprofile" ("status");
CREATE INDEX "students_st_goal_72b058_idx" ON "students_studentprofile" ("goal");
CREATE INDEX "students_st_created_f5606a_idx" ON "students_studentprofile" ("created_at");

CREATE INDEX "attendance__student_76a8d7_idx" ON "attendance_attendance" ("student_id", "date");
CREATE INDEX "attendance__date_61f2e1_idx" ON "attendance_attendance" ("date");
CREATE INDEX "attendance__is_pres_772c00_idx" ON "attendance_attendance" ("is_present");

CREATE INDEX "memberships_student_85dd7a_idx" ON "memberships_membership" ("student_id", "is_active");
CREATE INDEX "memberships_end_dat_dd07db_idx" ON "memberships_membership" ("end_date");

CREATE INDEX "payments_pa_student_2663d2_idx" ON "payments_payment" ("student_id", "status");
CREATE INDEX "payments_pa_payment_1d6e55_idx" ON "payments_payment" ("payment_date");
CREATE INDEX "payments_pa_status_7ad4af_idx" ON "payments_payment" ("status");
