-- ==========================================
-- Shresht Library Management System
-- PostgreSQL Database Schema for Supabase
-- ==========================================
-- Supabase Project Connection Details:
-- URL: https://crrfhaaqeainuqzkmged.supabase.co
-- Publishable Key: sb_publishable_m0z-t34QvHCIjmiFc9n4mQ_yy6epwbt
-- ==========================================

-- 1. Custom Users & Roles
CREATE TABLE "accounts_customuser" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "password" varchar(128) NOT NULL,
    "last_login" timestamp with time zone NULL,
    "is_superuser" boolean NOT NULL,
    "username" varchar(150) NOT NULL UNIQUE,
    "first_name" varchar(150) NOT NULL,
    "last_name" varchar(150) NOT NULL,
    "is_staff" boolean NOT NULL,
    "date_joined" timestamp with time zone NOT NULL,
    "email" varchar(254) NULL UNIQUE,
    "mobile" varchar(15) NULL UNIQUE,
    "role" varchar(20) NOT NULL,
    "otp" varchar(6) NULL,
    "otp_expiry" timestamp with time zone NULL,
    "is_active" boolean NOT NULL,
    "supabase_uid" uuid NULL UNIQUE
);

-- 2. Staff Administrators
CREATE TABLE "accounts_adminuser" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "username" varchar(150) NOT NULL UNIQUE,
    "password" varchar(128) NOT NULL,
    "first_name" varchar(150) NOT NULL,
    "last_name" varchar(150) NOT NULL,
    "email" varchar(254) NULL UNIQUE,
    "mobile" varchar(15) NULL UNIQUE,
    "role" varchar(20) NOT NULL,
    "permissions" jsonb NOT NULL,
    "is_active" boolean NOT NULL,
    "date_joined" timestamp with time zone NOT NULL,
    "last_login" timestamp with time zone NULL,
    "supabase_uid" uuid NULL UNIQUE,
    "created_by_id" bigint NULL REFERENCES "accounts_adminuser" ("id") ON DELETE SET NULL
);

-- 3. Student Profiles
CREATE TABLE "students_studentprofile" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "goal" varchar(50) NOT NULL,
    "dob" date NULL,
    "caste" varchar(50) NULL,
    "address" text NULL,
    "profile_photo" varchar(100) NULL,
    "parent_mobile" varchar(15) NULL,
    "user_id" bigint NOT NULL UNIQUE REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE
);

-- 4. Referral Tracking
CREATE TABLE "students_referralcode" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "code" varchar(20) NOT NULL UNIQUE,
    "used_by_count" integer NOT NULL,
    "benefit_given" varchar(255) NULL,
    "student_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE
);

CREATE TABLE "students_referralhistory" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "applied_at" timestamp with time zone NOT NULL,
    "referred_student_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE,
    "referrer_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE
);

-- 5. Secure QR Attendance Generator
CREATE TABLE "attendance_qrcode" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "code" varchar(255) NOT NULL UNIQUE,
    "valid_date" date NOT NULL,
    "is_expired" boolean NOT NULL,
    "expiry_timestamp" timestamp with time zone NOT NULL,
    "created_by_id" bigint NULL REFERENCES "accounts_adminuser" ("id") ON DELETE SET NULL
);

CREATE TABLE "attendance_attendance" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "date" date NOT NULL,
    "time_in" time NOT NULL,
    "is_manual" boolean NOT NULL,
    "student_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE,
    "qr_code_id" bigint NULL REFERENCES "attendance_qrcode" ("id") ON DELETE SET NULL
);

-- 6. Memberships Pricing Plans
CREATE TABLE "memberships_membershipplan" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(100) NOT NULL,
    "duration_months" integer NOT NULL,
    "price" numeric(10, 2) NOT NULL,
    "description" text NULL,
    "is_active" boolean NOT NULL
);

CREATE TABLE "memberships_membership" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "start_date" date NOT NULL,
    "end_date" date NOT NULL,
    "status" varchar(20) NOT NULL,
    "student_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE,
    "plan_id" bigint NOT NULL REFERENCES "memberships_membershipplan" ("id") ON DELETE RESTRICT
);

-- 7. Payment Ledger Transactions
CREATE TABLE "payments_payment" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "amount" numeric(10, 2) NOT NULL,
    "status" varchar(20) NOT NULL,
    "payment_mode" varchar(20) NOT NULL,
    "payment_date" date NOT NULL,
    "transaction_id" varchar(100) NULL,
    "receipt_url" varchar(200) NULL,
    "notes" text NULL,
    "membership_id" bigint NULL REFERENCES "memberships_membership" ("id") ON DELETE SET NULL,
    "student_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE
);

-- 8. Library Seats Layout Map
CREATE TABLE "seats_seat" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "floor" varchar(50) NOT NULL,
    "row" varchar(10) NOT NULL,
    "seat_number" varchar(10) NOT NULL,
    "status" varchar(20) NOT NULL
);

CREATE TABLE "seats_seatassignment" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "assigned_date" date NOT NULL,
    "released_date" date NULL,
    "seat_id" bigint NOT NULL REFERENCES "seats_seat" ("id") ON DELETE CASCADE,
    "student_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE
);

-- 9. Firebase FCM Push Notifications Channel
CREATE TABLE "notifications_notification" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(200) NOT NULL,
    "body" text NOT NULL,
    "type" varchar(20) NOT NULL,
    "target_group" varchar(20) NOT NULL,
    "sent_at" timestamp with time zone NOT NULL
);

CREATE TABLE "notifications_devicetoken" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "token" text NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "student_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE
);

CREATE TABLE "notifications_studentnotification" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "is_read" boolean NOT NULL,
    "read_at" timestamp with time zone NULL,
    "notification_id" bigint NOT NULL REFERENCES "notifications_notification" ("id") ON DELETE CASCADE,
    "student_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE
);

-- 10. Library Info, Achievers Showcase, and Student Reviews
CREATE TABLE "library_libraryinfo" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "rules" text NOT NULL,
    "facilities" text NOT NULL,
    "about" text NOT NULL
);

CREATE TABLE "library_achiever" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(100) NOT NULL,
    "photo" varchar(100) NULL,
    "achievement" varchar(255) NOT NULL,
    "year" integer NOT NULL
);

CREATE TABLE "library_review" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "rating" integer NOT NULL,
    "comment" text NOT NULL,
    "is_approved" boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "student_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE
);

-- 11. Study Timer and Hour Goals
CREATE TABLE "study_studygoal" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "date" date NOT NULL,
    "target_hours" numeric(5, 2) NOT NULL,
    "achieved_hours" numeric(5, 2) NOT NULL,
    "student_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE
);

CREATE TABLE "study_studysession" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "start_time" timestamp with time zone NOT NULL,
    "end_time" timestamp with time zone NULL,
    "duration_minutes" integer NOT NULL,
    "student_id" bigint NOT NULL REFERENCES "accounts_customuser" ("id") ON DELETE CASCADE
);

-- 12. Global Systems Settings & Action Activity Logs
CREATE TABLE "core_globalsetting" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "key" varchar(100) NOT NULL UNIQUE,
    "value" text NOT NULL,
    "description" text NULL
);

CREATE TABLE "core_activitylog" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "action" varchar(255) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    "ip_address" varchar(45) NULL,
    "details" jsonb NOT NULL,
    "user_id" bigint NULL REFERENCES "accounts_customuser" ("id") ON DELETE SET NULL,
    "admin_id" bigint NULL REFERENCES "accounts_adminuser" ("id") ON DELETE SET NULL
);
