CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);



CREATE TABLE IF NOT EXISTS accounts_adminuser (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    username character varying(150) NOT NULL,
    email character varying(254),
    password character varying(128) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    mobile character varying(15),
    role character varying(20) NOT NULL,
    permissions jsonb NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    last_login timestamp with time zone,
    supabase_uid uuid,
    created_by_id bigint,
    profile_image character varying(100),
    CONSTRAINT accounts_adminuser_pkey PRIMARY KEY (id),
    CONSTRAINT accounts_adminuser_created_by_id_02f160a4_fk_accounts_ FOREIGN KEY (created_by_id) REFERENCES accounts_adminuser (id)
);

CREATE TABLE IF NOT EXISTS accounts_authtokenrevocation (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    token_hash character varying(64) NOT NULL,
    jti character varying(255) NOT NULL,
    user_identifier character varying(255) NOT NULL,
    revoked_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone,
    CONSTRAINT accounts_authtokenrevocation_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS accounts_customuser (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254),
    mobile character varying(15),
    role character varying(20) NOT NULL,
    otp character varying(128),
    otp_expiry timestamp with time zone,
    is_active boolean NOT NULL,
    supabase_uid uuid,
    otp_attempts integer NOT NULL,
    CONSTRAINT accounts_customuser_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS auth_group (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(150) NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS core_globalsetting (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    key character varying(100) NOT NULL,
    value text NOT NULL,
    description text,
    CONSTRAINT core_globalsetting_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS django_content_type (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS django_migrations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

CREATE TABLE IF NOT EXISTS library_achiever (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    photo character varying(100),
    achievement character varying(255) NOT NULL,
    year integer NOT NULL,
    created_at timestamp with time zone,
    goal character varying(100),
    is_active boolean NOT NULL,
    is_featured boolean NOT NULL,
    "order" integer NOT NULL,
    CONSTRAINT library_achiever_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS library_appconfig (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    is_premium_gating_enabled boolean NOT NULL,
    expiry_dialog_title character varying(200) NOT NULL,
    expiry_dialog_message text NOT NULL,
    allow_non_premium_notifications boolean NOT NULL,
    allow_non_premium_library_info boolean NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    allow_non_premium_sliders boolean NOT NULL,
    default_allowed_study_minutes integer NOT NULL,
    expired_student_permissions jsonb NOT NULL,
    CONSTRAINT library_appconfig_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS library_databasefile (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    data bytea NOT NULL,
    content_type character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT library_databasefile_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS library_facility (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    icon_key character varying(50) NOT NULL,
    description text,
    is_active boolean NOT NULL,
    "order" integer NOT NULL,
    image character varying(100),
    CONSTRAINT library_facility_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS library_homeslider (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    title character varying(200) NOT NULL,
    subtitle character varying(200) NOT NULL,
    image character varying(100),
    link_url character varying(500) NOT NULL,
    is_active boolean NOT NULL,
    sort_order integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT library_homeslider_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS library_libraryinfo (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    library_name character varying(255) NOT NULL,
    logo character varying(255) NOT NULL,
    banner_image character varying(255),
    description text NOT NULL,
    established_year integer,
    owner_name character varying(255) NOT NULL,
    contact_number character varying(50) NOT NULL,
    email character varying(255) NOT NULL,
    website character varying(255),
    opening_time time without time zone NOT NULL,
    closing_time time without time zone NOT NULL,
    weekly_off character varying(100),
    total_capacity integer NOT NULL,
    available_seats integer NOT NULL,
    address_line1 character varying(255) NOT NULL,
    address_line2 character varying(255),
    area character varying(100) NOT NULL,
    city character varying(100) NOT NULL,
    state character varying(100) NOT NULL,
    country character varying(100) NOT NULL,
    pin_code character varying(20) NOT NULL,
    latitude numeric(10,6) NOT NULL,
    longitude numeric(10,6) NOT NULL,
    google_map_url character varying(500),
    wifi boolean,
    ac boolean,
    cctv boolean,
    drinking_water boolean,
    lockers boolean,
    charging_points boolean,
    parking boolean,
    reading_area boolean,
    computer_access boolean,
    printing boolean,
    facebook_url character varying(255),
    instagram_url character varying(255),
    whatsapp_number character varying(50),
    telegram_url character varying(255),
    youtube_url character varying(255),
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    updated_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT library_libraryinfo_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS memberships_membershipplan (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    duration_months integer NOT NULL,
    price numeric(10,2) NOT NULL,
    description text,
    is_active boolean NOT NULL,
    benefits jsonb NOT NULL,
    created_at timestamp with time zone,
    duration_days integer NOT NULL,
    sort_order integer NOT NULL,
    updated_at timestamp with time zone,
    CONSTRAINT memberships_membershipplan_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS seats_floor (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying(50) NOT NULL,
    description text,
    "order" integer NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT seats_floor_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS attendance_holiday (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    date date NOT NULL,
    title character varying(120) NOT NULL,
    description text,
    is_active boolean NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    created_by_id bigint,
    CONSTRAINT attendance_holiday_pkey PRIMARY KEY (id),
    CONSTRAINT attendance_holiday_created_by_id_752fc2d0_fk_accounts_ FOREIGN KEY (created_by_id) REFERENCES accounts_adminuser (id)
);

CREATE TABLE IF NOT EXISTS attendance_qrcode (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    code character varying(255) NOT NULL,
    valid_date date NOT NULL,
    is_expired boolean NOT NULL,
    expiry_timestamp timestamp with time zone NOT NULL,
    created_by_id bigint,
    created_at timestamp with time zone,
    expires_at timestamp with time zone,
    generation_method character varying(20) NOT NULL,
    is_active boolean NOT NULL,
    qr_hash text NOT NULL,
    token uuid,
    CONSTRAINT attendance_qrcode_pkey PRIMARY KEY (id),
    CONSTRAINT attendance_qrcode_created_by_id_8fb5d10a_fk_accounts_ FOREIGN KEY (created_by_id) REFERENCES accounts_adminuser (id)
);

CREATE TABLE IF NOT EXISTS notifications_notification (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    title character varying(200) NOT NULL,
    body text NOT NULL,
    type character varying(30) NOT NULL,
    target_group character varying(20) NOT NULL,
    sent_at timestamp with time zone,
    created_at timestamp with time zone,
    created_by_id bigint,
    failure_count integer NOT NULL,
    goal_filter character varying(50),
    scheduled_at timestamp with time zone,
    send_email boolean NOT NULL,
    send_push boolean NOT NULL,
    send_sms boolean NOT NULL,
    status_filter character varying(20),
    success_count integer NOT NULL,
    target character varying(20) NOT NULL,
    total_recipients integer NOT NULL,
    audience character varying(20) NOT NULL,
    background_image character varying(100),
    description text NOT NULL,
    display_mode character varying(20) NOT NULL,
    event_date date,
    expires_at timestamp with time zone,
    layout character varying(20) NOT NULL,
    link_button_text character varying(100) NOT NULL,
    link_url character varying(200) NOT NULL,
    recurring_time time without time zone,
    subtitle character varying(300) NOT NULL,
    CONSTRAINT notifications_notification_pkey PRIMARY KEY (id),
    CONSTRAINT notifications_notifi_created_by_id_44297423_fk_accounts_ FOREIGN KEY (created_by_id) REFERENCES accounts_adminuser (id)
);

CREATE TABLE IF NOT EXISTS core_activitylog (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    action character varying(255) NOT NULL,
    timestamp timestamp with time zone NOT NULL,
    ip_address inet,
    details jsonb NOT NULL,
    user_id bigint,
    admin_id bigint,
    CONSTRAINT core_activitylog_pkey PRIMARY KEY (id),
    CONSTRAINT core_activitylog_admin_id_6073fa99_fk_accounts_adminuser_id FOREIGN KEY (admin_id) REFERENCES accounts_adminuser (id),
    CONSTRAINT core_activitylog_user_id_8705e516_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES accounts_customuser (id)
);

CREATE TABLE IF NOT EXISTS library_review (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    rating integer NOT NULL,
    comment text NOT NULL,
    is_approved boolean NOT NULL,
    created_at timestamp with time zone,
    student_id bigint NOT NULL,
    approved_at timestamp with time zone,
    approved_by_id bigint,
    rejection_reason text,
    updated_at timestamp with time zone,
    CONSTRAINT library_review_pkey PRIMARY KEY (id),
    CONSTRAINT library_review_approved_by_id_9b229f8b_fk_accounts_adminuser_id FOREIGN KEY (approved_by_id) REFERENCES accounts_adminuser (id),
    CONSTRAINT library_review_student_id_b855301a_fk_accounts_customuser_id FOREIGN KEY (student_id) REFERENCES accounts_customuser (id)
);

CREATE TABLE IF NOT EXISTS notifications_admininboxnotification (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    title character varying(200) NOT NULL,
    message text NOT NULL,
    type character varying(50) NOT NULL,
    is_read boolean NOT NULL,
    related_id character varying(100),
    created_at timestamp with time zone NOT NULL,
    student_id bigint,
    CONSTRAINT notifications_admininboxnotification_pkey PRIMARY KEY (id),
    CONSTRAINT notifications_admini_student_id_96823e67_fk_accounts_ FOREIGN KEY (student_id) REFERENCES accounts_customuser (id)
);

CREATE TABLE IF NOT EXISTS notifications_devicetoken (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    token text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    student_id bigint NOT NULL,
    CONSTRAINT notifications_devicetoken_pkey PRIMARY KEY (id),
    CONSTRAINT notifications_device_student_id_206fe9a0_fk_accounts_ FOREIGN KEY (student_id) REFERENCES accounts_customuser (id)
);

CREATE TABLE IF NOT EXISTS students_referralcode (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    code character varying(20) NOT NULL,
    used_by_count integer NOT NULL,
    benefit_given character varying(255),
    student_id bigint NOT NULL,
    CONSTRAINT students_referralcode_pkey PRIMARY KEY (id),
    CONSTRAINT students_referralcod_student_id_ca5fc2fe_fk_accounts_ FOREIGN KEY (student_id) REFERENCES accounts_customuser (id)
);

CREATE TABLE IF NOT EXISTS students_referralhistory (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    applied_at timestamp with time zone NOT NULL,
    referred_student_id bigint NOT NULL,
    referrer_id bigint NOT NULL,
    CONSTRAINT students_referralhistory_pkey PRIMARY KEY (id),
    CONSTRAINT students_referralhis_referred_student_id_9f6f3db5_fk_accounts_ FOREIGN KEY (referred_student_id) REFERENCES accounts_customuser (id),
    CONSTRAINT students_referralhis_referrer_id_bb28ff49_fk_accounts_ FOREIGN KEY (referrer_id) REFERENCES accounts_customuser (id)
);

CREATE TABLE IF NOT EXISTS students_studentprofile (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    goal character varying(50) NOT NULL,
    dob date,
    caste character varying(50),
    address text,
    profile_photo character varying(100),
    parent_mobile character varying(15),
    user_id bigint NOT NULL,
    created_at timestamp with time zone,
    gender character varying(20) NOT NULL,
    middle_name character varying(100),
    preferred_language character varying(10) NOT NULL,
    referred_by_id bigint,
    status character varying(20) NOT NULL,
    student_id character varying(20),
    suspended_at timestamp with time zone,
    suspended_by_id bigint,
    suspension_reason text,
    updated_at timestamp with time zone,
    allowed_study_minutes integer,
    joining_date date NOT NULL,
    CONSTRAINT students_studentprofile_pkey PRIMARY KEY (id),
    CONSTRAINT students_studentprof_referred_by_id_65c9f295_fk_students_ FOREIGN KEY (referred_by_id) REFERENCES students_studentprofile (id),
    CONSTRAINT students_studentprof_suspended_by_id_2f16f156_fk_accounts_ FOREIGN KEY (suspended_by_id) REFERENCES accounts_adminuser (id),
    CONSTRAINT students_studentprof_user_id_43a83eee_fk_accounts_ FOREIGN KEY (user_id) REFERENCES accounts_customuser (id)
);

CREATE TABLE IF NOT EXISTS study_studysession (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone,
    duration_minutes integer NOT NULL,
    student_id bigint NOT NULL,
    paused_minutes integer NOT NULL,
    status character varying(20) NOT NULL,
    CONSTRAINT study_studysession_pkey PRIMARY KEY (id),
    CONSTRAINT study_studysession_student_id_4613795f_fk_accounts_ FOREIGN KEY (student_id) REFERENCES accounts_customuser (id)
);

CREATE TABLE IF NOT EXISTS token_blacklist_outstandingtoken (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id bigint,
    jti character varying(255) NOT NULL,
    CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id),
    CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_accounts_ FOREIGN KEY (user_id) REFERENCES accounts_customuser (id)
);

CREATE TABLE IF NOT EXISTS accounts_customuser_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT accounts_customuser_groups_pkey PRIMARY KEY (id),
    CONSTRAINT accounts_customuser__customuser_id_bc55088e_fk_accounts_ FOREIGN KEY (customuser_id) REFERENCES accounts_customuser (id),
    CONSTRAINT accounts_customuser_groups_group_id_86ba5f9e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES auth_group (id)
);

CREATE TABLE IF NOT EXISTS auth_permission (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES django_content_type (id)
);

CREATE TABLE IF NOT EXISTS django_admin_log (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id),
    CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES django_content_type (id),
    CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES accounts_customuser (id)
);

CREATE TABLE IF NOT EXISTS memberships_membership (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    start_date date NOT NULL,
    end_date date NOT NULL,
    status character varying(20) NOT NULL,
    student_id bigint NOT NULL,
    plan_id bigint NOT NULL,
    created_at timestamp with time zone,
    created_by_id bigint,
    is_active boolean NOT NULL,
    notes text,
    plan_name_snapshot character varying(100) NOT NULL,
    price_snapshot numeric(10,2) NOT NULL,
    renewal_count integer NOT NULL,
    CONSTRAINT memberships_membership_pkey PRIMARY KEY (id),
    CONSTRAINT memberships_membersh_created_by_id_098854cb_fk_accounts_ FOREIGN KEY (created_by_id) REFERENCES accounts_adminuser (id),
    CONSTRAINT memberships_membersh_plan_id_a999e2c0_fk_membershi FOREIGN KEY (plan_id) REFERENCES memberships_membershipplan (id),
    CONSTRAINT memberships_membersh_student_id_aa07aea9_fk_accounts_ FOREIGN KEY (student_id) REFERENCES accounts_customuser (id)
);

CREATE TABLE IF NOT EXISTS seats_seatrow (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    label character varying(10) NOT NULL,
    "order" integer NOT NULL,
    floor_id bigint NOT NULL,
    CONSTRAINT seats_seatrow_pkey PRIMARY KEY (id),
    CONSTRAINT seats_seatrow_floor_id_d4f49e54_fk_seats_floor_id FOREIGN KEY (floor_id) REFERENCES seats_floor (id)
);

CREATE TABLE IF NOT EXISTS attendance_attendance (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    date date NOT NULL,
    time_in time without time zone NOT NULL,
    is_manual boolean NOT NULL,
    student_id bigint NOT NULL,
    qr_code_id bigint,
    is_present boolean NOT NULL,
    marked_at timestamp with time zone,
    marked_by_id bigint,
    method character varying(20) NOT NULL,
    note text,
    late_mark boolean NOT NULL,
    time_out time without time zone,
    total_hours character varying(10),
    under_time boolean NOT NULL,
    CONSTRAINT attendance_attendance_pkey PRIMARY KEY (id),
    CONSTRAINT attendance_attendanc_marked_by_id_0698c76f_fk_accounts_ FOREIGN KEY (marked_by_id) REFERENCES accounts_adminuser (id),
    CONSTRAINT attendance_attendanc_qr_code_id_e23eb1f8_fk_attendanc FOREIGN KEY (qr_code_id) REFERENCES attendance_qrcode (id),
    CONSTRAINT attendance_attendanc_student_id_94863613_fk_accounts_ FOREIGN KEY (student_id) REFERENCES accounts_customuser (id)
);

CREATE TABLE IF NOT EXISTS notifications_notificationimage (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    image character varying(100) NOT NULL,
    sort_order integer NOT NULL,
    notification_id bigint NOT NULL,
    CONSTRAINT notifications_notificationimage_pkey PRIMARY KEY (id),
    CONSTRAINT notifications_notifi_notification_id_433e3be0_fk_notificat FOREIGN KEY (notification_id) REFERENCES notifications_notification (id)
);

CREATE TABLE IF NOT EXISTS notifications_studentnotification (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    is_read boolean NOT NULL,
    read_at timestamp with time zone,
    notification_id bigint NOT NULL,
    student_id bigint NOT NULL,
    delivered_at timestamp with time zone,
    email_delivered boolean NOT NULL,
    push_delivered boolean NOT NULL,
    sms_delivered boolean NOT NULL,
    CONSTRAINT notifications_studentnotification_pkey PRIMARY KEY (id),
    CONSTRAINT notifications_studen_notification_id_c183c280_fk_notificat FOREIGN KEY (notification_id) REFERENCES notifications_notification (id),
    CONSTRAINT notifications_studen_student_id_269c68ed_fk_accounts_ FOREIGN KEY (student_id) REFERENCES accounts_customuser (id)
);

CREATE TABLE IF NOT EXISTS token_blacklist_blacklistedtoken (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL,
    CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id),
    CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES token_blacklist_outstandingtoken (id)
);

CREATE TABLE IF NOT EXISTS accounts_customuser_user_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT accounts_customuser_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT accounts_customuser__customuser_id_0deaefae_fk_accounts_ FOREIGN KEY (customuser_id) REFERENCES accounts_customuser (id),
    CONSTRAINT accounts_customuser__permission_id_aea3d0e5_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES auth_permission (id)
);

CREATE TABLE IF NOT EXISTS auth_group_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES auth_permission (id),
    CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES auth_group (id)
);

CREATE TABLE IF NOT EXISTS payments_payment (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    amount numeric(10,2) NOT NULL,
    status character varying(20) NOT NULL,
    payment_mode character varying(20) NOT NULL,
    payment_date date NOT NULL,
    transaction_id character varying(100),
    receipt_url character varying(100),
    notes text,
    membership_id bigint,
    student_id bigint NOT NULL,
    created_at timestamp with time zone,
    method character varying(20) NOT NULL,
    paid_at timestamp with time zone,
    payment_id character varying(30),
    recorded_by_id bigint,
    refund_amount numeric(10,2),
    refund_reason text,
    refunded_at timestamp with time zone,
    transaction_ref character varying(100),
    verified_at timestamp with time zone,
    verified_by_id bigint,
    CONSTRAINT payments_payment_pkey PRIMARY KEY (id),
    CONSTRAINT payments_payment_membership_id_68ea25d2_fk_membershi FOREIGN KEY (membership_id) REFERENCES memberships_membership (id),
    CONSTRAINT payments_payment_recorded_by_id_11b293af_fk_accounts_ FOREIGN KEY (recorded_by_id) REFERENCES accounts_adminuser (id),
    CONSTRAINT payments_payment_student_id_b5fab56a_fk_accounts_customuser_id FOREIGN KEY (student_id) REFERENCES accounts_customuser (id),
    CONSTRAINT payments_payment_verified_by_id_d4a4b387_fk_accounts_ FOREIGN KEY (verified_by_id) REFERENCES accounts_adminuser (id)
);

CREATE TABLE IF NOT EXISTS seats_seat (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    floor character varying(50) NOT NULL,
    row character varying(10) NOT NULL,
    seat_number character varying(10) NOT NULL,
    status character varying(20) NOT NULL,
    assigned_at timestamp with time zone,
    assigned_by_id bigint,
    notes text,
    student_id bigint,
    row_ref_id bigint,
    is_reserved_for_girls boolean NOT NULL,
    CONSTRAINT seats_seat_pkey PRIMARY KEY (id),
    CONSTRAINT seats_seat_assigned_by_id_d98ab468_fk_accounts_adminuser_id FOREIGN KEY (assigned_by_id) REFERENCES accounts_adminuser (id),
    CONSTRAINT seats_seat_row_ref_id_9cd08093_fk_seats_seatrow_id FOREIGN KEY (row_ref_id) REFERENCES seats_seatrow (id),
    CONSTRAINT seats_seat_student_id_9f4f5265_fk_accounts_customuser_id FOREIGN KEY (student_id) REFERENCES accounts_customuser (id)
);

CREATE TABLE IF NOT EXISTS seats_seatassignment (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    assigned_date date NOT NULL,
    released_date date,
    seat_id bigint NOT NULL,
    student_id bigint NOT NULL,
    CONSTRAINT seats_seatassignment_pkey PRIMARY KEY (id),
    CONSTRAINT seats_seatassignment_seat_id_d5ddd646_fk_seats_seat_id FOREIGN KEY (seat_id) REFERENCES seats_seat (id),
    CONSTRAINT seats_seatassignment_student_id_cab95c5c_fk_accounts_ FOREIGN KEY (student_id) REFERENCES accounts_customuser (id)
);

CREATE TABLE IF NOT EXISTS seats_seatchangelog (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    action character varying(30) NOT NULL,
    reason text,
    changed_at timestamp with time zone NOT NULL,
    changed_by_id bigint,
    previous_seat_id bigint,
    seat_id bigint NOT NULL,
    student_id bigint,
    CONSTRAINT seats_seatchangelog_pkey PRIMARY KEY (id),
    CONSTRAINT seats_seatchangelog_changed_by_id_cdd2a8f0_fk_accounts_ FOREIGN KEY (changed_by_id) REFERENCES accounts_adminuser (id),
    CONSTRAINT seats_seatchangelog_previous_seat_id_322f1f6b_fk_seats_seat_id FOREIGN KEY (previous_seat_id) REFERENCES seats_seat (id),
    CONSTRAINT seats_seatchangelog_seat_id_d31cdd48_fk_seats_seat_id FOREIGN KEY (seat_id) REFERENCES seats_seat (id),
    CONSTRAINT seats_seatchangelog_student_id_75b8adc9_fk_accounts_ FOREIGN KEY (student_id) REFERENCES accounts_customuser (id)
);

CREATE INDEX IF NOT EXISTS accounts_adminuser_created_by_id_02f160a4 ON accounts_adminuser (created_by_id);

CREATE INDEX IF NOT EXISTS accounts_adminuser_email_5110578e_like ON accounts_adminuser (email varchar_pattern_ops);

CREATE UNIQUE INDEX IF NOT EXISTS accounts_adminuser_email_key ON accounts_adminuser (email);

CREATE INDEX IF NOT EXISTS accounts_adminuser_mobile_3d5b9327_like ON accounts_adminuser (mobile varchar_pattern_ops);

CREATE UNIQUE INDEX IF NOT EXISTS accounts_adminuser_mobile_key ON accounts_adminuser (mobile);

CREATE UNIQUE INDEX IF NOT EXISTS accounts_adminuser_supabase_uid_key ON accounts_adminuser (supabase_uid);

CREATE INDEX IF NOT EXISTS accounts_adminuser_username_4d9b2ca6_like ON accounts_adminuser (username varchar_pattern_ops);

CREATE UNIQUE INDEX IF NOT EXISTS accounts_adminuser_username_key ON accounts_adminuser (username);

CREATE INDEX IF NOT EXISTS accounts_au_expires_474335_idx ON accounts_authtokenrevocation (expires_at);

CREATE INDEX IF NOT EXISTS accounts_authtokenrevocation_jti_53823217 ON accounts_authtokenrevocation (jti);

CREATE INDEX IF NOT EXISTS accounts_authtokenrevocation_jti_53823217_like ON accounts_authtokenrevocation (jti varchar_pattern_ops);

CREATE INDEX IF NOT EXISTS accounts_authtokenrevocation_token_hash_69826360_like ON accounts_authtokenrevocation (token_hash varchar_pattern_ops);

CREATE UNIQUE INDEX IF NOT EXISTS accounts_authtokenrevocation_token_hash_key ON accounts_authtokenrevocation (token_hash);

CREATE INDEX IF NOT EXISTS accounts_customuser_email_4fd8e7ce_like ON accounts_customuser (email varchar_pattern_ops);

CREATE UNIQUE INDEX IF NOT EXISTS accounts_customuser_email_key ON accounts_customuser (email);

CREATE INDEX IF NOT EXISTS accounts_customuser_mobile_a211a2ea_like ON accounts_customuser (mobile varchar_pattern_ops);

CREATE UNIQUE INDEX IF NOT EXISTS accounts_customuser_mobile_key ON accounts_customuser (mobile);

CREATE UNIQUE INDEX IF NOT EXISTS accounts_customuser_supabase_uid_key ON accounts_customuser (supabase_uid);

CREATE INDEX IF NOT EXISTS accounts_customuser_username_722f3555_like ON accounts_customuser (username varchar_pattern_ops);

CREATE UNIQUE INDEX IF NOT EXISTS accounts_customuser_username_key ON accounts_customuser (username);

CREATE INDEX IF NOT EXISTS accounts_customuser_groups_customuser_id_bc55088e ON accounts_customuser_groups (customuser_id);

CREATE UNIQUE INDEX IF NOT EXISTS accounts_customuser_groups_customuser_id_group_id_c074bdcb_uniq ON accounts_customuser_groups (customuser_id, group_id);

CREATE INDEX IF NOT EXISTS accounts_customuser_groups_group_id_86ba5f9e ON accounts_customuser_groups (group_id);

CREATE UNIQUE INDEX IF NOT EXISTS accounts_customuser_user_customuser_id_permission_9632a709_uniq ON accounts_customuser_user_permissions (customuser_id, permission_id);

CREATE INDEX IF NOT EXISTS accounts_customuser_user_permissions_customuser_id_0deaefae ON accounts_customuser_user_permissions (customuser_id);

CREATE INDEX IF NOT EXISTS accounts_customuser_user_permissions_permission_id_aea3d0e5 ON accounts_customuser_user_permissions (permission_id);

CREATE INDEX IF NOT EXISTS attendance__date_61f2e1_idx ON attendance_attendance (date);

CREATE INDEX IF NOT EXISTS attendance__is_pres_772c00_idx ON attendance_attendance (is_present);

CREATE INDEX IF NOT EXISTS attendance__student_76a8d7_idx ON attendance_attendance (student_id, date);

CREATE INDEX IF NOT EXISTS attendance_attendance_marked_by_id_0698c76f ON attendance_attendance (marked_by_id);

CREATE INDEX IF NOT EXISTS attendance_attendance_qr_code_id_e23eb1f8 ON attendance_attendance (qr_code_id);

CREATE INDEX IF NOT EXISTS attendance_attendance_student_id_94863613 ON attendance_attendance (student_id);

CREATE UNIQUE INDEX IF NOT EXISTS attendance_attendance_student_id_date_167892e4_uniq ON attendance_attendance (student_id, date);

CREATE INDEX IF NOT EXISTS attendance__date_3ffd05_idx ON attendance_holiday (date, is_active);

CREATE INDEX IF NOT EXISTS attendance_holiday_created_by_id_752fc2d0 ON attendance_holiday (created_by_id);

CREATE UNIQUE INDEX IF NOT EXISTS attendance_holiday_date_key ON attendance_holiday (date);

CREATE INDEX IF NOT EXISTS attendance_qrcode_code_d9ecc3f5_like ON attendance_qrcode (code varchar_pattern_ops);

CREATE UNIQUE INDEX IF NOT EXISTS attendance_qrcode_code_key ON attendance_qrcode (code);

CREATE INDEX IF NOT EXISTS attendance_qrcode_created_by_id_8fb5d10a ON attendance_qrcode (created_by_id);

CREATE UNIQUE INDEX IF NOT EXISTS attendance_qrcode_token_key ON attendance_qrcode (token);

CREATE INDEX IF NOT EXISTS auth_group_name_a6ea08ec_like ON auth_group (name varchar_pattern_ops);

CREATE UNIQUE INDEX IF NOT EXISTS auth_group_name_key ON auth_group (name);

CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9 ON auth_group_permissions (group_id);

CREATE UNIQUE INDEX IF NOT EXISTS auth_group_permissions_group_id_permission_id_0cd325b0_uniq ON auth_group_permissions (group_id, permission_id);

CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e ON auth_group_permissions (permission_id);

CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b ON auth_permission (content_type_id);

CREATE UNIQUE INDEX IF NOT EXISTS auth_permission_content_type_id_codename_01ab375a_uniq ON auth_permission (content_type_id, codename);

CREATE INDEX IF NOT EXISTS core_activitylog_admin_id_6073fa99 ON core_activitylog (admin_id);

CREATE INDEX IF NOT EXISTS core_activitylog_user_id_8705e516 ON core_activitylog (user_id);

CREATE INDEX IF NOT EXISTS core_globalsetting_key_50b930ca_like ON core_globalsetting (key varchar_pattern_ops);

CREATE UNIQUE INDEX IF NOT EXISTS core_globalsetting_key_key ON core_globalsetting (key);

CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb ON django_admin_log (content_type_id);

CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6 ON django_admin_log (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS django_content_type_app_label_model_76bd3d3b_uniq ON django_content_type (app_label, model);

CREATE INDEX IF NOT EXISTS django_session_expire_date_a5c62663 ON django_session (expire_date);

CREATE INDEX IF NOT EXISTS django_session_session_key_c0390e0f_like ON django_session (session_key varchar_pattern_ops);

CREATE INDEX IF NOT EXISTS library_databasefile_name_c1664fa0_like ON library_databasefile (name varchar_pattern_ops);

CREATE UNIQUE INDEX IF NOT EXISTS library_databasefile_name_key ON library_databasefile (name);

CREATE INDEX IF NOT EXISTS library_review_approved_by_id_9b229f8b ON library_review (approved_by_id);

CREATE INDEX IF NOT EXISTS library_review_student_id_b855301a ON library_review (student_id);

CREATE INDEX IF NOT EXISTS memberships_end_dat_dd07db_idx ON memberships_membership (end_date);

CREATE INDEX IF NOT EXISTS memberships_membership_created_by_id_098854cb ON memberships_membership (created_by_id);

CREATE INDEX IF NOT EXISTS memberships_membership_plan_id_a999e2c0 ON memberships_membership (plan_id);

CREATE INDEX IF NOT EXISTS memberships_membership_student_id_aa07aea9 ON memberships_membership (student_id);

CREATE INDEX IF NOT EXISTS memberships_student_85dd7a_idx ON memberships_membership (student_id, is_active);

CREATE INDEX IF NOT EXISTS notifications_admininboxnotification_student_id_96823e67 ON notifications_admininboxnotification (student_id);

CREATE INDEX IF NOT EXISTS notifications_devicetoken_student_id_206fe9a0 ON notifications_devicetoken (student_id);

CREATE INDEX IF NOT EXISTS notifications_notification_created_by_id_44297423 ON notifications_notification (created_by_id);

CREATE INDEX IF NOT EXISTS notifications_notificationimage_notification_id_433e3be0 ON notifications_notificationimage (notification_id);

CREATE INDEX IF NOT EXISTS notifications_studentnotification_notification_id_c183c280 ON notifications_studentnotification (notification_id);

CREATE INDEX IF NOT EXISTS notifications_studentnotification_student_id_269c68ed ON notifications_studentnotification (student_id);

CREATE INDEX IF NOT EXISTS payments_pa_payment_1d6e55_idx ON payments_payment (payment_date);

CREATE INDEX IF NOT EXISTS payments_pa_status_7ad4af_idx ON payments_payment (status);

CREATE INDEX IF NOT EXISTS payments_pa_student_2663d2_idx ON payments_payment (student_id, status);

CREATE INDEX IF NOT EXISTS payments_payment_membership_id_68ea25d2 ON payments_payment (membership_id);

CREATE INDEX IF NOT EXISTS payments_payment_payment_id_5ab18190_like ON payments_payment (payment_id varchar_pattern_ops);

CREATE UNIQUE INDEX IF NOT EXISTS payments_payment_payment_id_key ON payments_payment (payment_id);

CREATE INDEX IF NOT EXISTS payments_payment_recorded_by_id_11b293af ON payments_payment (recorded_by_id);

CREATE INDEX IF NOT EXISTS payments_payment_student_id_b5fab56a ON payments_payment (student_id);

CREATE INDEX IF NOT EXISTS payments_payment_verified_by_id_d4a4b387 ON payments_payment (verified_by_id);

CREATE INDEX IF NOT EXISTS seats_floor_name_cba6808a_like ON seats_floor (name varchar_pattern_ops);

CREATE UNIQUE INDEX IF NOT EXISTS seats_floor_name_key ON seats_floor (name);

CREATE INDEX IF NOT EXISTS seats_seat_assigned_by_id_d98ab468 ON seats_seat (assigned_by_id);

CREATE UNIQUE INDEX IF NOT EXISTS seats_seat_floor_row_seat_number_a2e25ffa_uniq ON seats_seat (floor, row, seat_number);

CREATE INDEX IF NOT EXISTS seats_seat_row_ref_id_9cd08093 ON seats_seat (row_ref_id);

CREATE UNIQUE INDEX IF NOT EXISTS seats_seat_student_id_key ON seats_seat (student_id);

CREATE INDEX IF NOT EXISTS seats_seatassignment_seat_id_d5ddd646 ON seats_seatassignment (seat_id);

CREATE INDEX IF NOT EXISTS seats_seatassignment_student_id_cab95c5c ON seats_seatassignment (student_id);

CREATE INDEX IF NOT EXISTS seats_seatchangelog_changed_by_id_cdd2a8f0 ON seats_seatchangelog (changed_by_id);

CREATE INDEX IF NOT EXISTS seats_seatchangelog_previous_seat_id_322f1f6b ON seats_seatchangelog (previous_seat_id);

CREATE INDEX IF NOT EXISTS seats_seatchangelog_seat_id_d31cdd48 ON seats_seatchangelog (seat_id);

CREATE INDEX IF NOT EXISTS seats_seatchangelog_student_id_75b8adc9 ON seats_seatchangelog (student_id);

CREATE INDEX IF NOT EXISTS seats_seatrow_floor_id_d4f49e54 ON seats_seatrow (floor_id);

CREATE UNIQUE INDEX IF NOT EXISTS seats_seatrow_floor_id_label_289d368e_uniq ON seats_seatrow (floor_id, label);

CREATE INDEX IF NOT EXISTS students_referralcode_code_066e8579_like ON students_referralcode (code varchar_pattern_ops);

CREATE UNIQUE INDEX IF NOT EXISTS students_referralcode_code_key ON students_referralcode (code);

CREATE INDEX IF NOT EXISTS students_referralcode_student_id_ca5fc2fe ON students_referralcode (student_id);

CREATE INDEX IF NOT EXISTS students_referralhistory_referred_student_id_9f6f3db5 ON students_referralhistory (referred_student_id);

CREATE INDEX IF NOT EXISTS students_referralhistory_referrer_id_bb28ff49 ON students_referralhistory (referrer_id);

CREATE INDEX IF NOT EXISTS students_st_created_f5606a_idx ON students_studentprofile (created_at);

CREATE INDEX IF NOT EXISTS students_st_goal_72b058_idx ON students_studentprofile (goal);

CREATE INDEX IF NOT EXISTS students_st_status_6012f4_idx ON students_studentprofile (status);

CREATE INDEX IF NOT EXISTS students_st_student_58f688_idx ON students_studentprofile (student_id);

CREATE INDEX IF NOT EXISTS students_studentprofile_referred_by_id_65c9f295 ON students_studentprofile (referred_by_id);

CREATE INDEX IF NOT EXISTS students_studentprofile_student_id_4817d513_like ON students_studentprofile (student_id varchar_pattern_ops);

CREATE UNIQUE INDEX IF NOT EXISTS students_studentprofile_student_id_key ON students_studentprofile (student_id);

CREATE INDEX IF NOT EXISTS students_studentprofile_suspended_by_id_2f16f156 ON students_studentprofile (suspended_by_id);

CREATE UNIQUE INDEX IF NOT EXISTS students_studentprofile_user_id_key ON students_studentprofile (user_id);

CREATE INDEX IF NOT EXISTS study_studysession_student_id_4613795f ON study_studysession (student_id);

CREATE UNIQUE INDEX IF NOT EXISTS token_blacklist_blacklistedtoken_token_id_key ON token_blacklist_blacklistedtoken (token_id);

CREATE INDEX IF NOT EXISTS token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON token_blacklist_outstandingtoken (jti varchar_pattern_ops);

CREATE UNIQUE INDEX IF NOT EXISTS token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq ON token_blacklist_outstandingtoken (jti);

CREATE INDEX IF NOT EXISTS token_blacklist_outstandingtoken_user_id_83bc629a ON token_blacklist_outstandingtoken (user_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260702161914_UpdateLibraryInfoSchema', '9.0.2');

COMMIT;

