# Generated by Django 6.0.6 on 2026-06-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0002_floor_seat_assigned_at_seat_assigned_by_seat_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_reserved_for_girls',
            field=models.BooleanField(default=False),
        ),
    ]
