# Generated by Django 5.1.15 on 2026-06-10 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminuser_delete_adminprofile'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_students', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('LIVE', 'Live'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended')], default='LIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='suspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_students', to='accounts.adminuser'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='goal',
            field=models.CharField(choices=[('UPSC', 'UPSC'), ('GPSC', 'GPSC'), ('CONSTABLE', 'Constable'), ('Banking', 'Banking'), ('Army', 'Army'), ('Teacher', 'Teacher'), ('Railway', 'Railway'), ('SSC', 'SSC'), ('CA', 'CA'), ('UPSC Exam', 'UPSC Exam'), ('SSC CGL', 'SSC CGL'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['student_id'], name='students_st_student_58f688_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['status'], name='students_st_status_6012f4_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['goal'], name='students_st_goal_72b058_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['created_at'], name='students_st_created_f5606a_idx'),
        ),
    ]
