# Generated by Django 6.0.6 on 2026-06-19 06:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile_created_at_studentprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='allowed_study_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
