# Generated by Django 6.0.6 on 2026-06-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='paused_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studysession',
            name='status',
            field=models.CharField(choices=[('starting', 'Starting'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='starting', max_length=20),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='StudyGoal',
        ),
    ]
