# Generated by Django 5.1.15 on 2026-06-10 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminuser_delete_adminprofile'),
        ('attendance', '0002_alter_qrcode_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to='accounts.adminuser'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='method',
            field=models.CharField(default='QR', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='generation_method',
            field=models.CharField(default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='qr_hash',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='attendance__student_76a8d7_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='attendance__date_61f2e1_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['is_present'], name='attendance__is_pres_772c00_idx'),
        ),
    ]
