# Generated by Django 5.1.15 on 2026-06-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='late_mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_hours',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='under_time',
            field=models.BooleanField(default=False),
        ),
    ]
