# Generated by Django 5.1.15 on 2026-06-10 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminuser_delete_adminprofile'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to='accounts.adminuser'),
        ),
        migrations.AddField(
            model_name='notification',
            name='failure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='goal_filter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='send_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='send_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='status_filter',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='success_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='target',
            field=models.CharField(default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='total_recipients',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentnotification',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentnotification',
            name='email_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentnotification',
            name='push_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentnotification',
            name='sms_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_group',
            field=models.CharField(choices=[('all', 'All'), ('active', 'Active'), ('expired', 'Expired'), ('specific', 'Specific'), ('ALL', 'All'), ('GROUP', 'Group'), ('INDIVIDUAL', 'Individual')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('push', 'Push'), ('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('all', 'All'), ('GENERAL', 'General'), ('ANNOUNCEMENT', 'Announcement'), ('PAYMENT', 'Payment'), ('ATTENDANCE', 'Attendance'), ('PLAN_EXPIRY', 'Plan Expiry'), ('SEAT_CHANGE', 'Seat Change'), ('HOLIDAY', 'Holiday')], default='push', max_length=30),
        ),
    ]
