# Generated by Django 6.0.6 on 2026-06-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_created_at_notification_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInboxNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('NEW_STUDENT', 'New Student'), ('PAYMENT', 'Payment'), ('SUPPORT', 'Support'), ('EXPIRING_SOON', 'Expiring Soon'), ('EXPIRED', 'Expired'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('related_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
