# Generated by Django 6.0.6 on 2026-06-12 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_admininboxnotification_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='audience',
            field=models.CharField(choices=[('all', 'All Students'), ('new', 'New Students (< 7 days)'), ('premium', 'Premium (Active Plan)'), ('non_premium', 'Non-Premium (No Active Plan)'), ('expired', 'Expired Plan'), ('selected', 'Selected Students')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='notifications/'),
        ),
        migrations.AddField(
            model_name='notification',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='display_mode',
            field=models.CharField(choices=[('one_time', 'One Time (remove after seen)'), ('persistent', 'Persistent (stays until dismissed)'), ('recurring', 'Recurring Daily')], default='persistent', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='layout',
            field=models.CharField(choices=[('text_only', 'Text Only'), ('half_image', 'Half Image'), ('full_image', 'Full Image'), ('background_image', 'Background Image')], default='text_only', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='link_button_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='link_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='recurring_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.CreateModel(
            name='NotificationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notifications/')),
                ('sort_order', models.IntegerField(default=0)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='notifications.notification')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
